### ISSUE TITLE
But - I can't unpause

### ISSUE THREAD

**Issue by brunocalado** [cswendrowski/FoundryVTT-Obligatory-Fishing-Minigame#2]
Hi.

I can't unpause the game. I used the find the culprit module to find out about this.

After remove your module I can pause/unpause the game again.

**Comment by MrPotatoZed** [comment]
Seeing the same thing. Can't unpause so long as OFM is active and default control scheme is used. Looks like the reel in control is conflicting with the core space function. Deactivating or changing the default control for reeling in to anything other than space fixes the behavior. Tested with normal mods and only OFM active. 

V10.286, 5e 2.0.3, OFM 1.1.0. No errors in console. Local install.
