### ISSUE TITLE
Fishing Spot Configuration page type does not appear to respect the "Display Page Title" checkbox being unmarked

### ISSUE THREAD

**Issue by silvative** [cswendrowski/FoundryVTT-Obligatory-Fishing-Minigame#3]
![image](https://user-images.githubusercontent.com/66365038/190909101-761c1467-2e57-4cf9-bc61-36dbb5231a3b.png)

Critical bug pls fix

**Comment by cswendrowski** [comment]
Fixed in v1.1.1
