### ISSUE TITLE
Reeling resets when you release the reel in button

### ISSUE THREAD

**Issue by Geekswordsman** [cswendrowski/FoundryVTT-Obligatory-Fishing-Minigame#4]
Foundry v10.286
Obligatory Fishing Minigame v1.1.0
Browser: Edge/Firefox

When reeling in a fish, if you release the reel in button the reel resets back to the bottom, no errors in console.

[Fishing_Minigame_Error.webm](https://user-images.githubusercontent.com/41522046/192353448-26530503-c1dc-46dd-ae7f-92f5099333a9.webm)

**Comment by DeVelox** [comment]
This seems to be an issue with `duration: parseInt(app.rod.baitWeight) * 1000` which always resolves to 0 for any "improved" values of less than the default 1. Using `parseFloat` fixes the issue.

**Comment by Unrhymed** [comment]
I made the change and it did not fix it for me
